sudo: false
dist: trusty
language: node_js

addons:
  apt:
    packages:
      - google-chrome-stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

node_js:
    - "6"

before_script:
    - npm install -g @angular/cli
    - ng build -prod
