sudo: false
dist: trusty

cache:
    directories:
        - node_modules

language: node_js

node_js:
    - "7"

addons:
  chrome: beta

env:
  - CHROME_BIN=/usr/bin/google-chrome-beta

before_script:
    - npm install -g @angular/cli
    - ng build --prod --skip-tests
