sudo: false
dist: trusty

language: node_js

node_js:
    - "7"

addons:
  chrome: beta

before_install:
  - google-chrome-beta --headless --no-sandbox --disable-gpu --remote-debugging-port=9222 http://localhost

before_script:
    - npm install -g @angular/cli
    - ng build -prod
