sudo: false
dist: trusty

language: node_js

node_js:
    - "7"

addons:
  chrome: beta

env:
  - GOOGLE_CHROME_BINARY=/usr/bin/google-chrome-beta

before_script:
    - npm install -g @angular/cli
    - ng build -prod
