sudo: false
dist: trusty

language: node_js

node_js:
    - "7"

addons:
  chrome: beta

before_install:
  - google-chrome-beta --headless --disable-gpu --remote-debugging-port=9222 http://www.google.com

before_script:
    - npm install --save-dev dpogue/karma-headless-chrome-launcher
    - npm install -g @angular/cli
    - ng build -prod
